"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import toast from "react-hot-toast";
import ProductTable from "@/components/admin/ProductTable";
import ProductCardList from "@/components/admin/ProductCard";
import { Product } from "@/src/types/product";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function AdminProductsPage() {
  const [products, setProducts] = useState<Product[]>([]);
  const [loading, setLoading] = useState(true);

  const ITEMS_PER_PAGE = 5;

  /* ================= FILTER STATES ================= */
  const [search, setSearch] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("all");
  const [collectionFilter, setCollectionFilter] = useState("all");
  const [priceRange, setPriceRange] = useState("all");
  const [page, setPage] = useState(1);


  /* ================= FILTER LOGIC ================= */
  const filteredProducts = products.filter((p) => {
    const matchesSearch =
      p.name.toLowerCase().includes(search.toLowerCase()) ||
      p.category.toLowerCase().includes(search.toLowerCase()) ||
      p.collection.toLowerCase().includes(search.toLowerCase());

    const matchesCategory =
      categoryFilter === "all" || p.category === categoryFilter;

    const matchesCollection =
      collectionFilter === "all" || p.collection === collectionFilter;

    const matchesPriceRange =
      priceRange === "all" ||
      (priceRange === "50000-150000" &&
        p.basePrice >= 50000 &&
        p.basePrice <= 150000) ||
      (priceRange === "150000-300000" &&
        p.basePrice > 150000 &&
        p.basePrice <= 300000) ||
      (priceRange === "300000+" && p.basePrice > 300000);


    return (
      matchesSearch &&
      matchesCategory &&
      matchesCollection &&
      matchesPriceRange

    );
  });

  /* ================= PAGINATION ================= */
  const totalPages = Math.ceil(filteredProducts.length / ITEMS_PER_PAGE);
  const paginatedProducts = filteredProducts.slice(
    (page - 1) * ITEMS_PER_PAGE,
    page * ITEMS_PER_PAGE
  );


  /* ================= FETCH PRODUCTS ================= */

  const fetchProducts = async () => {
    try {
      setLoading(true);

      const res = await fetch(
        "http://localhost:3000/api/admin/products",
        {
          headers: {
            Authorization: `Bearer ${localStorage.getItem("token") || ""}`
          }
        }
      );

      if (!res.ok) throw new Error();

      const data: Product[] = await res.json();
      setProducts(data);
    } catch {
      toast.error("Failed to load products");
    } finally {
      setLoading(false);
    }
  };

  /* ================= DELETE PRODUCT ================= */

  const deleteProduct = async (id: string) => {
    try {
      const res = await fetch(
        `http://localhost:3000/api/admin/products/${id}`,
        {
          method: "DELETE",
          headers: {
            Authorization: `Bearer ${localStorage.getItem("token") || ""}`
          }
        }
      );

      if (!res.ok) throw new Error();

      toast.success("Product deleted successfully");
      fetchProducts();
    } catch {
      toast.error("Failed to delete product");
    }
  };

  /* ================= EFFECT ================= */

  useEffect(() => {
    fetchProducts();
  }, []);

  useEffect(() => {
    setPage(1);
  }, [search, categoryFilter, collectionFilter, priceRange]);



  /* ================= REPORT GENERATION ================= */
  const generateProductReport = () => {
    const doc = new jsPDF();

    /* -------- HEADER -------- */
    doc.setFontSize(18);
    doc.text("Product Inventory Report", 14, 18);

    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text(
      `Generated on: ${new Date().toLocaleString()}`,
      14,
      26
    );

    doc.setTextColor(0);
    doc.text(`Total Products: ${filteredProducts.length}`, 150, 26);

    /* -------- TABLE -------- */
    autoTable(doc, {
      startY: 40,
      head: [[
        "Product Name",
        "Category",
        "Collection",
        "Base Price",
        "Status"
      ]],
      body: filteredProducts.map((p) => [
        p.name,
        p.category,
        p.collection,
        `LKR ${p.basePrice}`,
      ]),
      styles: {
        fontSize: 9
      },
      headStyles: {
        fillColor: [212, 175, 55] // gold
      }
    });

    /* -------- FOOTER -------- */
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        "Generated by ChronoLux Admin System",
        14,
        doc.internal.pageSize.height - 10
      );
    }

    doc.save("product-inventory-report.pdf");
  };

  /* ================= UI ================= */

  return (
    <div className="space-y-8">
      {/* HEADER */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white tracking-wide">
            Products
          </h1>
          <p className="text-sm text-gray-400">
            Manage inventory and generate product reports
          </p>
        </div>

        <div className="flex gap-3">
          <button
            onClick={generateProductReport}
            className="px-6 py-2 rounded-full
      border border-[#d4af37]
      text-[#d4af37] font-semibold
      hover:bg-[#d4af37] hover:text-black transition"
          >
            📄 Generate Report
          </button>

          <Link
            href="/admin/products/create"
            className="px-6 py-2 rounded-full bg-[#d4af37]
      text-black font-semibold hover:opacity-90 transition"
          >
            + Add Product
          </Link>
        </div>
      </div>

      {/* FILTER BAR */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-4 bg-black/40 border border-white/10 rounded-2xl p-4">
        {/* SEARCH */}
        <input
          placeholder="Search name / category / collection"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="px-4 py-2 rounded-xl bg-black border border-white/10
    text-white text-sm focus:border-[#d4af37] outline-none"
        />

        {/* CATEGORY */}
        <select
          value={categoryFilter}
          onChange={(e) => setCategoryFilter(e.target.value)}
          className="px-4 py-2 rounded-xl bg-black border border-white/10
    text-white text-sm"
        >
          <option value="all">All Categories</option>
          <option value="Men">Men</option>
          <option value="Women">Women</option>
          <option value="Unisex">Unisex</option>
        </select>

        {/* COLLECTION */}
        <select
          value={collectionFilter}
          onChange={(e) => setCollectionFilter(e.target.value)}
          className="px-4 py-2 rounded-xl bg-black border border-white/10
    text-white text-sm"
        >
          <option value="all">All Collections</option>
          <option value="Luxury">Luxury</option>
          <option value="Sport">Sport</option>
          <option value="Classic">Classic</option>
          <option value="Limited">Limited</option>
        </select>

        {/* PRICE */}
        <select
          value={priceRange}
          onChange={(e) => setPriceRange(e.target.value)}
          className="px-4 py-2 rounded-xl bg-black border border-white/10
  text-white text-sm"
        >
          <option value="all">All Prices</option>
          <option value="50000-150000">LKR 50,000 – 150,000</option>
          <option value="150000-300000">LKR 150,000 – 300,000</option>
          <option value="300000-500000">LKR 300,000 – 500,000</option>
          <option value="500000-1000000">LKR 500,000 – 1,000,000</option>
        </select>


      </div>

      <p className="text-sm text-gray-400">
        Showing {filteredProducts.length} of {products.length} products
      </p>



      {/* CONTENT */}
      {loading ? (
        <div className="py-20 text-center text-gray-400">Loading products...</div>
      ) : products.length === 0 ? (
        <div className="py-20 text-center text-gray-500">No products found</div>
      ) : (
        <>
          {/* Mobile */}
          <ProductCardList products={paginatedProducts} onDelete={deleteProduct} />

          {/* Desktop */}
          <ProductTable products={paginatedProducts} onDelete={deleteProduct} />

          {totalPages > 1 && (
            <div className="flex items-center justify-between mt-8 px-2">
              <button
                disabled={page === 1}
                onClick={() => setPage((p) => p - 1)}
                className="px-4 py-2 rounded-full border border-white/20
      text-sm text-gray-300 disabled:opacity-40 hover:border-[#d4af37]"
              >
                Previous
              </button>

              <span className="text-sm text-gray-400">
                Page <span className="text-white">{page}</span> of{" "}
                <span className="text-white">{totalPages}</span>
              </span>

              <button
                disabled={page === totalPages}
                onClick={() => setPage((p) => p + 1)}
                className="px-4 py-2 rounded-full border border-white/20
      text-sm text-gray-300 disabled:opacity-40 hover:border-[#d4af37]"
              >
                Next
              </button>
            </div>
          )}

        </>
      )}

    </div>
  );
}
